language: node_js
node_js:
  - 16.13.2

cache:
  yarn: true
  npm: false
  directories:
    - .cache

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  target-branch: gh-pages
  on:
    branch: master
