language: node_js
node_js: 
  - 12.18.4

cache: 
  yarn: true
  npm: false
  directories:
    - .cache

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: gh-pages